/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.economy.jsonc --env=production --include-runtime=false --strict-vars=false --env-interface=EconomyEnv worker-economy-configuration.d.ts` (hash: 8a34a4d608ce54f3fd0a69c09028a0e8)
interface __BaseEnv_EconomyEnv {
	DB: D1Database;
	SKYPILOT_ENVIRONMENT: string;
	ENABLE_PUBLIC_ECONOMY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_EconomyEnv {}
}
interface EconomyEnv extends __BaseEnv_EconomyEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SKYPILOT_ENVIRONMENT" | "ENABLE_PUBLIC_ECONOMY">> {}
}
