import type { PlayerAnalysis } from "@/lib/models";

export const demoPlayerAnalysis: PlayerAnalysis = {
  source: "demo",
  fetchedAt: "2026-08-08T20:00:00.000Z",
  cacheStatus: "demo",
  player: {
    username: "PilotExample",
    uuid: "demo-player-not-a-real-uuid",
    avatarUrl: null,
  },
  selectedProfileId: "demo-watermelon",
  notices: [
    "This is a clearly labeled demonstration profile. Its values are illustrative and are never presented as live Hypixel data.",
    "SkyPilot scores, valuations, and recommendations are independent estimates—not official Hypixel statistics.",
  ],
  profiles: [
    {
      id: "demo-watermelon",
      name: "Watermelon",
      gameMode: "Ironman",
      selected: true,
      lastSave: "2026-08-08T19:42:00.000Z",
      stats: [
        { key: "level", label: "SkyBlock Level", value: 287, unit: "level", note: "Official profile level" },
        { key: "purse", label: "Purse", value: 182_400_000, unit: "coins" },
        { key: "bank", label: "Bank", value: 614_800_000, unit: "coins" },
        { key: "networth", label: "Estimated Net Worth", value: 4_820_000_000, unit: "coins", note: "SkyPilot estimate" },
        { key: "mp", label: "Magical Power", value: 1104, unit: "count" },
        { key: "skill-average", label: "Skill Average", value: 49.6, unit: "level" },
        { key: "catacombs", label: "Catacombs", value: 38.7, unit: "level" },
        { key: "slayer", label: "Slayer XP", value: 3_580_000, unit: "xp" },
        { key: "minions", label: "Minion Slots", value: 28, unit: "count" },
        { key: "museum", label: "Museum Completion", value: 71, unit: "percent" },
      ],
      skills: [
        { key: "farming", label: "Farming", level: 58.3, progress: 83, xp: 92_000_000 },
        { key: "mining", label: "Mining", level: 60, progress: 100, xp: 128_000_000 },
        { key: "combat", label: "Combat", level: 60, progress: 100, xp: 131_000_000 },
        { key: "foraging", label: "Foraging", level: 37.8, progress: 78, xp: 18_000_000 },
        { key: "fishing", label: "Fishing", level: 45.4, progress: 40, xp: 44_000_000 },
        { key: "enchanting", label: "Enchanting", level: 60, progress: 100, xp: 124_000_000 },
        { key: "alchemy", label: "Alchemy", level: 50, progress: 100, xp: 55_000_000 },
      ],
      gear: [
        { slot: "Armor", name: "Fermento set", rarity: "LEGENDARY", status: "upgrade", note: "Two pieces are missing recombobulation." },
        { slot: "Weapon", name: "Hyperion", rarity: "MYTHIC", status: "strong", note: "Core upgrades detected." },
        { slot: "Mining", name: "Divan set", rarity: "MYTHIC", status: "upgrade", note: "Three gemstone slots can still improve." },
        { slot: "Pet", name: "Elephant", rarity: "LEGENDARY", status: "strong", note: "Level 100 with Green Bandana." },
      ],
      recommendations: [
        {
          id: "demo-accessories",
          title: "Complete four efficient accessory upgrades",
          reason: "They provide the strongest available account-wide combat value per coin before larger gear purchases.",
          category: "Accessories",
          priority: "very-high",
          estimatedCost: 18_400_000,
          estimatedBenefit: "+31 Magical Power",
          prerequisites: ["Access to the listed accessory families"],
          badge: "BEST VALUE",
          href: "/accessories",
        },
        {
          id: "demo-mining-gems",
          title: "Finish gemstone slots on your Divan set",
          reason: "Your mining progression is strong, so this immediately improves an activity you are already equipped to use.",
          category: "Mining",
          priority: "high",
          estimatedCost: 43_000_000,
          estimatedBenefit: "About +74 Mining Fortune",
          prerequisites: ["Unlocked gemstone chambers", "Available powder allocation"],
          badge: "HIGH IMPACT",
          href: "/mining",
        },
        {
          id: "demo-minion-slot",
          title: "Craft toward minion slot 29",
          reason: "Four low-cost unique crafts produce durable passive value and collection progress.",
          category: "Minions",
          priority: "high",
          estimatedCost: 6_700_000,
          estimatedBenefit: "+1 minion slot after 11 crafts",
          prerequisites: ["Craft the identified missing tiers"],
          badge: "CHEAP UPGRADE",
          href: "/minions",
        },
        {
          id: "demo-foraging",
          title: "Bring Foraging to level 40",
          reason: "It is the largest gap in an otherwise late-game skill profile and unlocks an efficient milestone target.",
          category: "Skills",
          priority: "medium",
          estimatedCost: 2_000_000,
          estimatedBenefit: "+2.2 levels and additional Strength",
          prerequisites: ["Choose an available foraging route"],
          badge: "REQUIRES GRIND",
          href: "/foraging",
        },
        {
          id: "demo-museum",
          title: "Raise Museum completion to 75%",
          reason: "Several low-value donations are missing before the next expensive completion band.",
          category: "Museum",
          priority: "long-term",
          estimatedCost: 82_000_000,
          estimatedBenefit: "+4% Museum completion",
          prerequisites: ["Verify soulbound and donation eligibility"],
          badge: "LONG TERM",
          href: "/museum",
        },
      ],
      strengths: ["End-game Mining setup", "Strong combat foundation", "High Magical Power", "Maxed core utility skills"],
      weaknesses: ["Foraging trails the profile", "Museum has efficient missing donations", "Farming armor has unfinished modifiers"],
      unavailable: ["Exact inventory valuation requires inventory API access", "Some Bestiary and Rift fields may be unavailable"],
    },
    {
      id: "demo-apple",
      name: "Apple",
      gameMode: "Normal",
      selected: false,
      lastSave: "2026-08-01T15:20:00.000Z",
      stats: [
        { key: "level", label: "SkyBlock Level", value: 96, unit: "level" },
        { key: "purse", label: "Purse", value: 8_300_000, unit: "coins" },
        { key: "bank", label: "Bank", value: 42_100_000, unit: "coins" },
        { key: "networth", label: "Estimated Net Worth", value: 288_000_000, unit: "coins", note: "SkyPilot estimate" },
        { key: "mp", label: "Magical Power", value: 392, unit: "count" },
        { key: "skill-average", label: "Skill Average", value: 27.4, unit: "level" },
      ],
      skills: [],
      gear: [],
      recommendations: [],
      strengths: ["Balanced early progression"],
      weaknesses: ["Magical Power is below the efficient range"],
      unavailable: [],
    },
  ],
};
