/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/player-gateway/wrangler.jsonc --env-file=cloudflare/player-gateway/.dev.vars.example --include-runtime=false --strict-vars=false cloudflare/player-gateway/worker-configuration.d.ts` (hash: c6ea944bd282bf83e6b52a6741cf83e4)
interface __BaseEnv_Env {
	PLAYER_CACHE: KVNamespace;
	PLAYER_ACTOR_LIMITER: RateLimit;
	PLAYER_GLOBAL_LIMITER: RateLimit;
	SKYPILOT_GATEWAY_VERSION: string;
	SKYPILOT_SITE_ORIGIN: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SKYPILOT_GATEWAY_VERSION" | "SKYPILOT_SITE_ORIGIN">> {}
}
